name: hsite
channels:
  - pytorch
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python=3.6.9
  - pytorch=1.5.0
  - cudatoolkit=10.2
  - easydict
  - matplotlib
  - numpy
  - pillow
  - pip
  - scikit-learn
  - yaml